[package]
name = "sample_gui"
version = "0.1.0"
authors = ["tesao <shimeji9@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.1.1"
chrono = "0.4.13"
libp2p = "0.22.0"
assert-type-eq = "0.1.0"